- become: yes
  hosts: all
  name: Install docker on amazonlinux2
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python-pip
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install docker-ce (centos) via amazon-linux-extras packages
      shell: "amazon-linux-extras install docker-ce docker-ce-cli containerd.io -y"

    - name: Enable containerd service at startup
      service:
        name: containerd
        state: started
        enabled: yes

    - name: Enable docker service at startup
      service:
        name: docker
        state: started
        enabled: yes
